version: '3'

services:
  miniircd_test:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ['nosetests']
    # entrypoint: ['nosetests', 'test.py:TestBasicStuff']
    network_mode: 'host'
    volumes:
      - ./:/home/src
